apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.global.namespace }}
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secrets.root_password }}
  MYSQL_PASSWORD: {{ .Values.mysql.secrets.mysql_password }}
