apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
spec:
  capacity:
    storage: {{ .Values.mysql.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageclass }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.mysql.backuppath }}   # stored on EC2
    type: DirectoryOrCreate

  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: {{ .Values.global.nodeSelector.label }}
          operator: In
          values:
          - {{ .Values.mysql.nodename }}

